### ISSUE TITLE
ZMNHDA Qubino Flush Dimmer multilevel switch current value not propagating from zwavejs to zwavejs2mqtt

### ISSUE THREAD

**Issue by NINE78** [zwave-js/zwave-js#2910]
### Version

Build/Run method

- [X] Docker -> running a Home Assistant supervised add-on

zwavejs2mqtt version: 1.1.0
zwavejs version: 6.1.3

### Describe the bug

For my Qubino (GOAP) ZMNHDA dimmers, I see multilevel switch ("current value") updates sent to Endpoints 0 and 1, but only Endpoint 1 is received in zwavejs2mqtt, this when manually toggling the light switch.

From zwavejs log:
```
15:34:46.396 SERIAL « 0x0109000400400326030094                                            (11 bytes)
15:34:46.398 CNTRLR   [Node 064] [~] [Multilevel Switch] currentValue: 63 => 0          [Endpoint 0]
15:34:46.399 SERIAL » [ACK]                                                                   (0x06)
15:34:46.402 DRIVER « [Node 064] [REQ] [ApplicationCommand]
                      └─[MultilevelSwitchCCReport]
                          current value: 0
15:34:46.407 CNTRLR   [Node 064] [~] [Multilevel Switch] currentValue: 63 => 0          [Endpoint 1]
15:34:47.336 SERIAL « 0x0110000400400a320221340000023b0000bd                              (18 bytes)
```

However in zwavejs2mqtt log, only 38-1 value is updated, which does not get picked up by the "Current Value" entity in HA (there is only one for the light):
`2021-02-10 15:34:46.411 INFO ZWAVE: Node 64: value updated: 38-1-currentValue 63 => 0`

### To Reproduce

1. toggle lights
2. observe only endpoint 1 coming through to zwavejs2mqtt in the logs

### Expected behavior

Also expect 64-38-0-currentValue to be updated

### Additional context

Logs attached
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5959164/zwavejs2mqtt.log)
[zwavejs_578.log](https://github.com/zwave-js/zwavejs2mqtt/files/5959168/zwavejs_578.log)

**Comment by AlCalzone** [comment]
This **should** be fixed with https://github.com/zwave-js/node-zwave-js/pull/2997 in the upcoming 8.x release. If not, feel free to reopen with new logs.

**Comment by bratanon** [comment]
Also seeing this issue with all ZMNHDD. 

Have re-interviewed the devices but still the same issue when turning off the lights. Turning on works fine.

Currently using z-wave js addon in HA 0.1.32 which includes Z-Wave JS 8.0.5

**Comment by AlCalzone** [comment]
Z-Wave JS 8.x includes some changes to endpoints/associations which might require compat flags for some devices. Please share a driver log of a re-interview, so I can use that to figure out which changes are necessary.

**Comment by bratanon** [comment]
Is "driver log" the same as I get from the Home Assistant addon for z-wave js?

Is there a way to filter the logs for a specific node? I have a lot of  nodes reporting all the time which clutter the logs.

With which serviery do you what the log? Debug? Info?

**Comment by AlCalzone** [comment]
Its this one - loglevel "debug" please:
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs

> Is there a way to filter the logs for a specific node?

zwavejs2mqtt should let you do that. If not, it's also okay.

**Comment by bratanon** [comment]
[node014.log](https://github.com/zwave-js/node-zwave-js/files/6877608/node014.log)

Hope this helps.

**Comment by bratanon** [comment]
Not sure if this also helps, but it seems like if i start with what I think is brightness level 50 and turn off the light, its correctly reflected in the UI. However, If i start with brightness level 30, its not working. it will still be turned on in the UI.
[node014_turn_off_30.log](https://github.com/zwave-js/node-zwave-js/files/6877698/node014_turn_off_30.log)
[node014_turn_off_50.log](https://github.com/zwave-js/node-zwave-js/files/6877699/node014_turn_off_50.log)

**Comment by AlCalzone** [comment]
@bratanon Please download the logfile as indicated in the documentation I linked you. The re-interview log you posted is just a small chunk of the whole thing and those logs are mixed with the application logs that just create noise.

**Comment by bratanon** [comment]
> @bratanon Please download the logfile as indicated in the documentation I linked you. The re-interview log you posted is just a small chunk of the whole thing and those logs are mixed with the application logs that just create noise.

Ok got it. Here is that.
[zwavejs_2021-07-26.log](https://github.com/zwave-js/node-zwave-js/files/6878646/zwavejs_2021-07-26.log)

**Comment by AlCalzone** [comment]
Ok, the interview log looks fine. The 50->0 log also looks fine, but in the 40->0 log the intermediate values are not sent by the device after the step to 30.

Honestly, this looks more like those reports either get lost or the device doesn't send them sometimes. I don't think we can realistically do something about it. zwave-js already polls if the device does not report on its own, but in this case it does (once).

You could try to use a Zniffer next to the device to figure out if it is actually sending the reports. 
If it is, you have a connectivity issue you should try and fix by re-arranging or adding some mains-powered device and/or healing the network.
If it doesn't, asking the Qubino support for help would be my recommentation

**Comment by fbietlot** [comment]
Hello,
First of all, Apologize if this is not the right place to share. I've some IT background but not a developper or expert and I'm not so familiar with add-ons, Zwave, .... . Any I try to do my best ;-)
I have a similar issue with ZMNHTD.
I can see the switch button but when I press it on Z-Wave JS to MQTT, it directly come back to it's original state (=off)
Here is the log:
```
2021-10-15 11:04:51.801 INFO ZWAVE: Calling api writeValue with args: [
{
nodeId: 10,
commandClass: 37,
endpoint: 0,
property: 'targetValue'
},
true,
{},
[length]: 3
]
2021-10-15 11:04:51.803 INFO ZWAVE: Writing true to 10-37-0-targetValue
2021-10-15 11:04:51.881 INFO ZWAVE: Node 10: value updated: 37-0-currentValue false => true
2021-10-15 11:04:51.886 INFO ZWAVE: Success zwave api call writeValue undefined
2021-10-15 11:04:52.945 INFO ZWAVE: Node 10: value updated: 37-0-currentValue true => false

```
My understanding was that there was a specific endpoint (1 ??) for the switch but here it seems to use endpoint 0 (the one the get the meter value ??) Again, not familiar, just trying to guess.

I have reach Qubino and here is the mail exchange hereunder.

I hope it can help the community and myself ;-) 

> On Fri, 8 Oct at 5:38 PM , Francois  wrote:
Hi have successfully added the Smat meter to my home assitant using an usb stick Aeotec ZW090 on RasberyPi.
As you can see in attachment I have a full list of entity to monitor the smartmeter.
I have also set the parameter 100 to 1	EP IR external relay dsbld, External relay enbld.
The module IKA232 is correctly wired to pin 4 and 5.
But I'm not able to find any entity to control 'on/off) the switch in home assitant.
Could you please assist me ?

Thanks and kr

François

____
Le lun. 11 oct. 2021 à 09:05, Qubino Support <support@qubino.com> a écrit :
Hello Francois,

Thank you very much for reaching out to us,

Once you set the parameter you must exclude (without reset it to defaults) and re-include the Smart Meter to make the change active. The device must do the integration (inclusion) since is at that point that the gateway do the interview with the Smart Meter and according to that generate all the entities.

I hope I was able to help you, if you have any additional questions please don't hesitate to ask.

p.s.: All the tickets that require verification on the gateways and the tickets that require testing will get answered latter as the ones that don't need any testing. We ask for your understanding and thank you for the patience.

Best regards,
Igor, Technical support
__________

On Tue, 12 Oct at 3:18 PM , Francois wrote:
Hi Igor,

Thank you for your swift and useful feedback.
I was aware of the need of inclusion and exclusion but it seems I missed something because after a new try, I'm now able to see a toggle button for the Smart meter.
Unfortunately It's not yet working because when I press the button to activate the external relay, the button comes automatically to off and nothing happens on my controlled device.
Here are some screenshots:
list of parameters
video showing what is happening
log of Homeassisatnt to the Smartmeter.


Thank you in advance for your help.

François
___________________
On Tue, Oct 12, 2021 at 3:53 PM Qubino Support <support@qubino.com> wrote:
Hello Francois,

Thank you for the feedback, that should not work like this.. when you trigger the switch the IKA do not trigger I suppose (you should hear it click)

Can you check the FW version of the Smart Meter it should be 7.11 but it is possible that is lower like 7.09.

p.s.: All the tickets that require verification on the gateways and the tickets that require testing will get answered latter as the ones that don't need any testing. We ask for your understanding and thank you for the patience.

Best regards,
Igor, Technical support


________________
On Tue, 12 Oct at 4:38 PM , Francois  wrote:
Hello

Version seems ok 
Indeed no click on IKA.

kr

François

: Device info
ZMNHTD
by Qubino
Firmware: 7.11
Z-Wave Info
Device ID: 9
Device Status: Alive
Device Ready: Yes
Secure: No


_______________
[nodes_dump.json.txt](https://github.com/zwave-js/node-zwave-js/files/7352398/nodes_dump.json.txt)
_

On Wed, Oct 13, 2021 at 10:47 AM Qubino Support <support@qubino.com> wrote:
Hello Francois,

Thanks, so we will exclude the wrong parameter (we have that in one of the older firmware) another possibility is the wrongly set lifeline. When you add the Ika or Bicom to the Smart Meter become a multi channel device (for the same reason must be excluded and re-included) and this have also to be set from the Gateway side. In the previous versions of the Home Assistant (open z-wave) the lifeline had to be set manually. I don't know if this is also your case but is worth to try. Home Assistant setting MC - Multi Channel lifeline One of our customer was kind enough to write us the tutorial to set this in the open z-wave integration of the HA (https://support.qubino.com/en/support/solutions/articles/44002125819-home-assistant-setting-mc-multi-channel-lifeline). It is dome for the 3 Phase Smart Meter but in this case as mentioned also the single phase smart meter communicate in MC lifeline. I hope that the tutorial can help you.


Best regards,
Igor, Technical support 

_______________________
François xxxxxx	Fri, Oct 15, 2021 at 11:06 AM
To: Qubino Support <support@qubino.com>
Hi Igor,

I spent a lot of time trying to fix this but it doesn't seems to work.
As far as I can see, the device is correctly set as Multichannel = true.
But the issue remains the same and I see some similar issue with Qubino by searching on google.
I hope it helps if I attached the node dump file from  node-zwave-js
Here are alos some log info:
2021-10-15 11:04:51.801 INFO ZWAVE: Calling api writeValue with args: [
{
nodeId: 10,
commandClass: 37,
endpoint: 0,
property: 'targetValue'
},
true,
{},
[length]: 3
]
2021-10-15 11:04:51.803 INFO ZWAVE: Writing true to 10-37-0-targetValue
2021-10-15 11:04:51.881 INFO ZWAVE: Node 10: value updated: 37-0-currentValue false => true
2021-10-15 11:04:51.886 INFO ZWAVE: Success zwave api call writeValue undefined
2021-10-15 11:04:52.945 INFO ZWAVE: Node 10: value updated: 37-0-currentValue true => false

Can you please check ?

Thanks 

François

> 

> ``

**Comment by AlCalzone** [comment]
@fbietlot could you ask the Qubino support for the actual Z-Wave command their device expects for setting up the association?

Depending on what your device supports, it would go through this list and do the first thing that's supported:
* Multi Channel, with `Association CC` support on the endpoints: On each endpoint, create an association with `Association CC`, target node 1
* Multi Channel, with `Multi Channel Association CC` support on the endpoints: On each endpoint, create an association with `Multi Channel Association CC`, target node 1, target endpoint 0
* Multi Channel, with `Multi Channel Association CC` support on the root device: On the root device, create an association with `Multi Channel Association CC`, target node 1, target endpoint 0
* Single Channel: On the root device, create an association with `Association CC`, target node 1

With this strategy, I believe I have ironed out most kinks in regards to real-world associations in `node-zwave-js`. But the steps you linked to seem to use "node 1, endpoint 1" as the association target, which the driver won't ever target on its own.

If target endpoint 1 is actually required, you'll have to set up the association manually. HomeAssistant doesn't let you do that yet and you'll need to resort to zwavejs2mqtt. But I'm not sure if it will let you create an association to Node 1, endpoint 1 there. @robertsLando?

**Comment by robertsLando** [comment]
You should be able to do it from associations dialog (try to write down endpoint manually if not listed), if not driverFunction is the only alternative

**Comment by AlCalzone** [comment]
> try to write down endpoint manually if not listed

That's what I wanted to hear :)

**Comment by robertsLando** [comment]
@AlCalzone Just checked, you cannot write an endpoint there, that's a select not a combobox :(

**Comment by andyboeh** [comment]
This looks related to the issues with the ZMNHDD that I'm also seeing (on all my four devices), similar to @bratanon. Did you ever find a solution and/or contact Qubino?

**Comment by robertsLando** [comment]
You can only try by using a driver function:

```js
const source = {
nodeId: 20,
endpoint: 1
}
const groupId = 1

const ass = {
nodeId: 1,
endpoint: 1
}
await driver.controller.addAssociations(source, groupId, [ass])
```

Edit it with the values needed

Edit (AlCalzone): Controller is likely node 1 :)

**Comment by fbietlot** [comment]
Thank you so much for taking the time to help me.
I have read a little bit about association and I try to add the association via the advanced driver function (I made some prinstcreen as it could be helpfull for newbie like me ;-) )
`const source = {
nodeId: 10,
endpoint: 1
}
const groupId = 1

const ass = {
nodeId: 1,
endpoint: 1
}
await driver.controller.addAssociations(source, groupId, [ass])`

Unfortunately I receive an error sayng that endpoint 1 does'nt exist for node10 .
Actually, I think that it's what I'm trying to do : add the endpoint 1 :-( (if it makes sense)

I **tryied** to check in the node dump .
[nodes_dump.json.txt](https://github.com/zwave-js/node-zwave-js/files/7354109/nodes_dump.json.txt)
I see somethink like : 
`endpointsCount | 2`
but can't find any reference to endpoint1

I must admit I'm not sure the issue is coming from zwavejs. But I have no clue how I can investigate more. 
I read about zwave pc controller. I don't know if it can help but I will try to understand more



</body>
</html>


![Screenshot 2021-10-15 163118](https://user-images.githubusercontent.com/46578620/137504687-6fa47f9a-2d6b-4a06-9fc4-5e295fa7f4a7.jpg)
![Screenshot 2021-10-15 163214](https://user-images.githubusercontent.com/46578620/137504725-9a80b025-207a-4a7d-b834-7102e2b949d5.jpg)
![Screenshot 2021-10-15 163248](https://user-images.githubusercontent.com/46578620/137504746-5cc55e64-5ed4-4a9e-8a13-991ca1611f2c.jpg)

**Comment by robertsLando** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
```
    "endpointsCount": 2,
    "endpointIndizes": [],
```
Something is weird here. @fbietlot can you re-interview the node, make a [driver log](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs) of that, loglevel `debug` or `silly` and **attach** it here as a file?

You cannot add endpoints, a device tells us which endpoints it has. Also: are you sure that you **excluded** and **re-included** the device **without resetting** after changing the config parameter?

**Comment by fbietlot** [comment]
At first I missed the exclusion and reinclusion part. Then I was even not able to see the Binary Swicth
But after correct exlusion and red reinclusion, the binary switch is now there.... but not working.
I will try to get you the log
PS: Thank you

**Comment by fbietlot** [comment]
OK I did a re-interview and here are the log and node.json
[zwavejs_2021-10-15.log](https://github.com/zwave-js/node-zwave-js/files/7354390/zwavejs_2021-10-15.log)
[nodes_dump.json (2).txt](https://github.com/zwave-js/node-zwave-js/files/7354392/nodes_dump.json.2.txt)

As far as I understand in the log the endpoint for the switch was found ..
But...
2021-10-15T15:17:32.620Z CNTRLR   [Node 010] Endpoints seem unnecessary b/c they have different device classes, 
                                  ignoring all...

**Comment by AlCalzone** [comment]
Ok we can work around that with a compat flag. Will add it later.

**Comment by fbietlot** [comment]
@AlCalzone so I maybe find something that can be fixed ?
😁😁😁 if yes, so glad ;-) My first participation to an issue on github ;-)

**Comment by fbietlot** [comment]
Hello again, 
Thanks to your comment, I've try to understand compat flag logic for preserveEndpoints.
My intention was to change the config file to add the compat flag.
I've created a custom config file in ZwaveJStoMQTT in store/config
![image](https://user-images.githubusercontent.com/46578620/137724018-19238087-4787-42df-8f32-ba8be82f04c6.png)

check config
![image](https://user-images.githubusercontent.com/46578620/137724097-17174783-7c38-408c-af10-25bc64d716e0.png)


I have Save -restart (even reboot) - reinterviewed.
But my custom config file doesn't seems to be taken into account
`2021-10-18T11:32:00.844Z DRIVER « [Node 010] [REQ] [ApplicationCommand]
                                  └─[ManufacturerSpecificCCReport]
                                      manufacturer id: 0x0159
                                      product type:    0x07
                                      product id:      0x52`
`2021-10-18T11:32:02.981Z CNTRLR   [Node 010] Embedded device config loaded`

zwavejs2mqtt: 5.8.0
zwave-js: 8.4.1
Core
Version
core-2021.10.4
Supervisor
Version
supervisor-2021.10.0

@robertsLando did I miss something to activate custom config file ?
[zwavejs_2021-10-18.log](https://github.com/zwave-js/node-zwave-js/files/7364528/zwavejs_2021-10-18.log)

**Comment by robertsLando** [comment]
Seems you have followed all the steps described in: https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files

Just found the error in logs: 

```js
2021-10-18T11:04:38.140Z CONFIG   Error parsing config file zmnhtd.json: The device config file is malformed!
                                  packages/config/config/devices/zmnhtd.json:
                                  paramInformation is not an object
```

**Comment by fbietlot** [comment]
indeed I didn't notice this message :-(
This is actually strange because I've just copy/paste the config file "packages/config/config/devices/0x0159/zmnhtd.json" and add the compat flag.
I made another test without the compat flag (so just exact copy of the file on github)
Same error : -(


`2021-10-18T12:34:05.937Z CONFIG   Error parsing config file zmnhtd.json: The device config file is malformed!
                                  packages/config/config/devices/zmnhtd.json:
                                  paramInformation is not an object`

Reading the documentation :  https://zwave-js.github.io/zwavejs2mqtt/#/device-support/custom-device-files

<html>
<body>


paramInformation | An array of the configuration parameters the device supports. See below for details.
-- | --



</body>
</html>

From my undersatnding : paramInformation is not an object but an array (so I'm not sure the error message is accurate)

**Comment by AlCalzone** [comment]
The problem is that we recently switched the config file format. You copied a new file which is not yet understood by the driver version installed on your system.
If @robertsLando pushes a new update of zwavejs2mqtt, you should be able to use that to load the new file.

**Comment by robertsLando** [comment]
@AlCalzone If beta 2 supports it he can use `master` tag on docker and it will work

**Comment by AlCalzone** [comment]
yeah beta supports it

**Comment by robertsLando** [comment]
@fbietlot So just use `master` tag if you are using docker

**Comment by fbietlot** [comment]
Sorry but I know a little bit what docker is but no clue how to interact with it and how to use "master"  :-(  (Still a lot to learn...)
More easy for me, I picked the old version of the config file (with object instead of array) and change the compat flag.
and good news !!
The binary switch is now linked to endpoint 2
![image](https://user-images.githubusercontent.com/46578620/137734675-4bee7b51-7305-4876-a7d1-d82b0c209ba1.png)



So I'm progressing.
Unfortunatly I'm not home so I can not check if the relay is correctly working. Will check later and keep you posted.

In the meanwhile, I received this answer from Qubino.
I must read it with more attention later because it's not self speaking to me :-( 

<

>  Hello Francois,
> 
> Thank you for the links, going trough that and your emails again I notice something that was not make the things fit as it have to be.
> 
> The command class that you use 37 is not a part of the command classes that are used in the Smart Meter you can see al the Command Classes that our Smart Meter support in the extended user manual that you can find on this page ( Qubino Smart Meter ) check the pages 48 and 49, because of that is not possible that you will get any reply from there. The command class 37 refers to COMMAND_CLASS_HRV_STATUS  0x37, if you need to know the status of the IKA you must use the switch binary command class COMMAND_CLASS_SWITCH_BINARY  0x25
> a command 25 02 sent to the Smart Meter it will trigger the meter to reply on the status. The Command have to be sent to the endpoint 2 as the IKA endpoint is that one.
> 
> As you may see in the video the reports are sent to the COMMAND_CLASS_SWITCH_BINARY  0x25 under the command 03 which is the SWITCH_BINARY_REPORT. You can see in the video and in the gif that the reports are sent and you can also hear the IKA trigger when the command On or Off is sent.
> 
> In the second gif I send the COMMAND_CLASS_HRV_STATUS  0x37 and as you may see there's no response.
> 
> Best regards,
> Igor, Technical support 


>
![PCc_Check1PhIkaCC37No](https://user-images.githubusercontent.com/46578620/137736231-1e5d4b72-5706-4f06-bdf5-1228d4e17634.gif)
![PCc_Check1PhIkaReports](https://user-images.githubusercontent.com/46578620/137736235-1650a458-f055-427d-9581-d80e6ffcafda.gif)

https://user-images.githubusercontent.com/46578620/137736237-e0fb9674-43c2-48c2-ba36-4c13d384dd92.mp4

**Comment by AlCalzone** [comment]
Regarding Qubino's response
> The command class that you use 37 [...] The command class 37 refers to COMMAND_CLASS_HRV_STATUS 0x37

They are confusing decimal 37 (hexadecimal `0x25`) with hexadecimal `0x37` (decimal 55).
37 = 0x25 = SWITCH_BINARY

**Comment by robertsLando** [comment]
> Sorry but I know a little bit what docker is but no clue how to interact with it and how to use "master" :-( (Still a lot to learn...)

What build method are yopu using? If docker instead of using `latest` tag use `master`

**Comment by fbietlot** [comment]
> > Sorry but I know a little bit what docker is but no clue how to interact with it and how to use "master" :-( (Still a lot to learn...)
> 
> What build method are yopu using? If docker instead of using `latest` tag use `master`

I'm just clicking on install in Home Assistant Supervised 😳 😕

**Comment by robertsLando** [comment]
Oh ok so you are using hass addon, @blhoward2 how can he use docker images with hass os?

**Comment by blhoward2** [comment]
The only way to use a built docker image is by installing the Portainer addon, or you may be able to install the ssh addon and manually run docker (I'm not sure on that one). Otherwise he's limited to the zwavejs addon or the zwavejs2mqtt addon. 

https://community.home-assistant.io/t/home-assistant-community-add-on-portainer/68836

**Comment by QubinoHelp** [comment]
> They are confusing decimal 37 (hexadecimal `0x25`) with hexadecimal `0x37` (decimal 55).
> 37 = 0x25 = SWITCH_BINARY

Hi to all, yes I did assume that the command you're sending was in RAW so in hexadecimal, that's why the mistake. I didn't use the zvaveJS to zwave2mqtt as I was testing and checking the command with the PC controller and the Zniffer to see what is going on between the device and the z-wave controller. As you may see from the video and the Gif the Smart Meter reacts and  replies properly if the proper command is received.

@NINE78 I went again to the first message you send us and notice that you use the Parameter 100 set to 1 while the IKA is controlled setting the parameter 100 to 2
 2- Endpoints IR external relay (BICOM) disabled, Triac External relay (IKA) enabled
 
 After you do the change exclude the Smart Meter, wait at least 30 seconds and re-include it again.

**Comment by fbietlot** [comment]
Hi @QubinoHelp  thank you for the follow up. I understand the confusion.
Regarding param 100 as I don't have the infrared relay I set it up to 1 (and not 2)

"label": "EP IR external relay dsbld, External relay enbld",
"value": 1



I will try to install PC controller to also do some testing. But unfortunately I don't think I have the knowledge to deal with a Zniffer.
Back to the command send from ZwaveJS. here is the Raw log when I activate the 2 available binary switch 👍 

```
2021-10-19T08:56:48.999Z SERIAL » 0x010e00130a07600d0001250100250785                                  (16 bytes)
2021-10-19T08:56:49.004Z DRIVER » [Node 010] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      7
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[BinarySwitchCCSet]
                                        target value: false
2021-10-19T08:56:49.018Z SERIAL « [ACK]                                                                   (0x06)
2021-10-19T08:56:49.028Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-10-19T08:56:49.032Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:49.039Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-19T08:56:49.047Z SERIAL « 0x0107001307000003ef                                                 (9 bytes)
2021-10-19T08:56:49.049Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:49.052Z DRIVER « [REQ] [SendData]
                                    callback id:     7
                                    transmit status: OK
2021-10-19T08:56:49.066Z CNTRLR   [Node 010] [\~] [Binary Switch] currentValue: false => false       [Endpoint 1]
2021-10-19T08:56:50.085Z SERIAL » 0x010d00130a06600d0001250225088b                                    (15 bytes)
2021-10-19T08:56:50.086Z DRIVER » [Node 010] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      8
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 1
                                    └─[BinarySwitchCCGet]
2021-10-19T08:56:50.089Z SERIAL « [ACK]                                                                   (0x06)
2021-10-19T08:56:50.096Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-10-19T08:56:50.101Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:50.106Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-19T08:56:50.120Z SERIAL « 0x0107001308000002e1                                                 (9 bytes)
2021-10-19T08:56:50.122Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:50.126Z DRIVER « [REQ] [SendData]
                                    callback id:     8
                                    transmit status: OK
2021-10-19T08:56:50.138Z SERIAL « 0x010d0004000a07600d0100250300b1                                    (15 bytes)
2021-10-19T08:56:50.142Z CNTRLR   [Node 010] [\~] [Binary Switch] currentValue: false => false       [Endpoint 1]
2021-10-19T08:56:50.149Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:50.155Z DRIVER « [Node 010] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      1
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: false
2021-10-19T08:56:54.111Z SERIAL » 0x010e00130a07600d0002250100250988                                  (16 bytes)
2021-10-19T08:56:54.114Z DRIVER » [Node 010] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      9
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 2
                                    └─[BinarySwitchCCSet]
                                        target value: false
2021-10-19T08:56:54.124Z SERIAL « [ACK]                                                                   (0x06)
2021-10-19T08:56:54.134Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-10-19T08:56:54.137Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:54.142Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-19T08:56:54.155Z SERIAL « 0x0107001309000003e1                                                 (9 bytes)
2021-10-19T08:56:54.157Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:54.160Z DRIVER « [REQ] [SendData]
                                    callback id:     9
                                    transmit status: OK
2021-10-19T08:56:54.176Z CNTRLR   [Node 010] [\~] [Binary Switch] currentValue: false => false       [Endpoint 2]
2021-10-19T08:56:55.191Z SERIAL » 0x010d00130a06600d00022502250a8a                                    (15 bytes)
2021-10-19T08:56:55.193Z DRIVER » [Node 010] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      10
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 2
                                    └─[BinarySwitchCCGet]
2021-10-19T08:56:55.196Z SERIAL « [ACK]                                                                   (0x06)
2021-10-19T08:56:55.202Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-10-19T08:56:55.215Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:55.232Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-19T08:56:55.241Z SERIAL « 0x010700130a000002e3                                                 (9 bytes)
2021-10-19T08:56:55.242Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:55.244Z DRIVER « [REQ] [SendData]
                                    callback id:     10
                                    transmit status: OK
2021-10-19T08:56:55.253Z SERIAL « 0x010d0004000a07600d0200250300b2                                    (15 bytes)
2021-10-19T08:56:55.255Z CNTRLR   [Node 010] [\~] [Binary Switch] currentValue: false => false       [Endpoint 2]
2021-10-19T08:56:55.261Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T08:56:55.264Z DRIVER « [Node 010] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      2
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: false
```

>


I see some difference between your command (but not yet able to *decode this*)
DC08622a0141081325600D0002**2501FF**00DA97

**Comment by blhoward2** [comment]
It looks like your commanding false and it's reporting that it's already false. What happens if you set true?

**Comment by fbietlot** [comment]
sorry not the best example (I was focusing on message structure.)
Here is an example with true.
Set value to True
But report False

```
2021-10-19T07:29:31.852Z SERIAL » 0x010e00130a07600d00022501ff25057b                                  (16 bytes)
2021-10-19T07:29:31.854Z DRIVER » [Node 010] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      5
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 2
                                    └─[BinarySwitchCCSet]
                                        target value: true
2021-10-19T07:29:31.869Z SERIAL « [ACK]                                                                   (0x06)
2021-10-19T07:29:31.879Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-10-19T07:29:31.882Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T07:29:31.885Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-19T07:29:31.891Z SERIAL « 0x0107001305000003ed                                                 (9 bytes)
2021-10-19T07:29:31.893Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T07:29:31.896Z DRIVER « [REQ] [SendData]
                                    callback id:     5
                                    transmit status: OK
2021-10-19T07:29:31.908Z CNTRLR   [Node 010] [\~] [Binary Switch] currentValue: false => true        [Endpoint 2]
2021-10-19T07:29:32.925Z SERIAL » 0x010d00130a06600d00022502250686                                    (15 bytes)
2021-10-19T07:29:32.927Z DRIVER » [Node 010] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      6
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      0
                                    │ destination: 2
                                    └─[BinarySwitchCCGet]
2021-10-19T07:29:32.930Z SERIAL « [ACK]                                                                   (0x06)
2021-10-19T07:29:32.937Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-10-19T07:29:32.943Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T07:29:32.946Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-10-19T07:29:32.971Z SERIAL « 0x010d0004000a07600d0200250300b2                                    (15 bytes)
2021-10-19T07:29:32.976Z CNTRLR   [Node 010] [~] [Binary Switch] currentValue: true => false        [Endpoint 2]
2021-10-19T07:29:32.982Z SERIAL » [ACK]                                                                   (0x06)
2021-10-19T07:29:32.985Z DRIVER « [Node 010] [REQ] [ApplicationCommand]
                                  └─[MultiChannelCCCommandEncapsulation]
                                    │ source:      2
                                    │ destination: 0
                                    └─[BinarySwitchCCReport]
                                        current value: false
```

**Comment by AlCalzone** [comment]
@fbietlot please select your logs **after** pasting and click this button:
![grafik](https://user-images.githubusercontent.com/17641229/137942256-25c251c3-4cf5-44d9-8483-d6ffbe337342.png)
That will make it easier to digest.

**Comment by fbietlot** [comment]
Me again but with good news this time ;-)
@QubinoHelp : your suggestion was actually good for marameter 100 ;-)
@AlCalzone there is a confusion in the config file packages/config/config/devices/0x0159/zmnhtd.json

Here is the config

```
{
			"#": "100",
			"label": "Enable / Disable endpoints relays",
			"valueSize": 1,
			"minValue": 0,
			"maxValue": 3,
			"defaultValue": 0,
			"allowManualEntry": false,
			"options": [
				{
					"label": "EP IR external relay and External relay disabled",
					"value": 0
				},
				{
					"label": "EP IR external relay dsbld, External relay enbld",
					"value": 1
				},
				{
					"label": "EP IR external relay enbld, External relay dsbld",
					"value": 2
				},
				{
					"label": "EP IR external relay and External relay enabled",
					"value": 3
				}
			]
		}
```

Versus the manual

> Parameter no. 100 – Enable / Disable endpoints IR external relay (BICOM) and TRIAC External
> relay (IKA)
> Enabling IR external relay (BICOM) and Triac External relay (IKA) or both of them, means that
> endpoint (IR external relay) and endpoint (External relay) or both will be present on UI. Disabling
> them will result in hiding endpoints according to Parameter set value. Note that hiding endpoint
> has no impact on its functionality.
> Values (size is 1 byte dec):
> • default value 0
> • 0 - Endpoints IR external relay and External relay disabled
> • 1 - Endpoints IR external relay (BICOM) enabled, Triac External relay (IKA) disabled
> • **2- Endpoints IR external relay (BICOM) disabled, Triac External relay (IKA) enabled**
> • 3- Endpoints IR external relay and External relay enabled

Value 1 and 2 are inverted.

**Comment by AlCalzone** [comment]
That file needs to be reworked as a whole, but I'll at least fix this switchup for now. Great that you figured it out.

**Comment by AlCalzone** [comment]
@fbietlot can you verify that the changes made in #3555 match what you changed and make sense?
